create database BANKDATABASE;
USE BANKDATABASE;

CREATE TABLE CUSTOMER (
	CUSTID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FNAME VARCHAR(30) NOT NULL,
    MNAME VARCHAR(30),
    LTNAME VARCHAR(30) NOT NULL,
    CITY VARCHAR(15) NOT NULL,
    MOBILENO BIGINT(10) NOT NULL,
    OCCUPATION VARCHAR(10),
    DOB DATE NOT NULL,
    CHECK( CHAR_LENGTH(MOBILENO)=10)
);

CREATE TABLE BRANCH (
	BID VARCHAR(10) PRIMARY KEY,
    BNAME VARCHAR(30) NOT NULL,
    BCITY VARCHAR(30) NOT NULL,
    CHECK(CHAR_LENGTH(BID)=10)
);

CREATE TABLE LOAN (
	LOAN_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	CUSTID BIGINT,
    BID VARCHAR(10),
    LOAN_AMOUNT BIGINT,
    FOREIGN KEY (CUSTID) REFERENCES CUSTOMER(CUSTID),
    FOREIGN KEY (BID) REFERENCES BRANCH(BID)
);

CREATE TABLE BANK_ACCOUNT (
	ACNUMBER BIGINT PRIMARY KEY AUTO_INCREMENT,
	CUSTID BIGINT NOT NULL,
	BID VARCHAR(10) NOT NULL,
	OPENING_BALANCE BIGINT NOT NULL ,
	AOD DATE NOT NULL,
	ATYPE VARCHAR(10) NOT NULL,
	ASTATUS VARCHAR(10) NOT NULL,
    FOREIGN KEY (CUSTID) REFERENCES CUSTOMER(CUSTID),
    FOREIGN KEY (BID) REFERENCES BRANCH(BID),
    CHECK(ATYPE IN ('LOAN','SAVINGS','CURRENT')),
    CHECK(ASTATUS IN ('OPENED','CLOSED'))
);

CREATE TABLE TRANDETAILS (
	TNUMBER BIGINT PRIMARY KEY AUTO_INCREMENT,
    ACNUMBER BIGINT(12) NOT NULL,
    LOAN_ID BIGINT,
    DOT DATE NOT NULL,
    MEDIUM_OF_TRANSACTION VARCHAR(20) NOT NULL,
    TRANSACTION_TYPE VARCHAR(20) NOT NULL,
    TRANSACTION_AMOUNT BIGINT NOT NULL,
    FOREIGN KEY (ACNUMBER) REFERENCES BANK_ACCOUNT(ACNUMBER),
    FOREIGN KEY (LOAN_ID) REFERENCES LOAN(LOAN_ID),
    CHECK(MEDIUM_OF_TRANSACTION IN ('BT','CD')),
    CHECK(TRANSACTION_TYPE IN ('CREDIT')),
    CHECK(TRANSACTION_AMOUNT > 0)
);

